
CREATE TABLE TaiKhoan (
    TenDangNhap VARCHAR(50) PRIMARY KEY,
    MatKhau VARCHAR(100) NOT NULL,
    VaiTro ENUM('KHACH', 'NHANVIEN') NOT NULL
);

CREATE TABLE KhachHang (
    MaKH INT PRIMARY KEY AUTO_INCREMENT,
    TenKH VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    SDT VARCHAR(20) NOT NULL,
    /* YÊU CẦU MỚI: Thêm giới tính */
    GioiTinh ENUM('NAM', 'NU', 'KHAC') NULL,
    TenDangNhap VARCHAR(50) NOT NULL,
    FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoan(TenDangNhap)
);

CREATE TABLE NhanVien (
    MaNV INT PRIMARY KEY AUTO_INCREMENT,
    TenNV VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    TenDangNhap VARCHAR(50) NOT NULL,
    FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoan(TenDangNhap)
);

CREATE TABLE BoSuuTap (
    MaBST INT PRIMARY KEY AUTO_INCREMENT,
    TenBST VARCHAR(100) NOT NULL,
    MoTa TEXT
);

CREATE TABLE SanPham (
    MaSP INT PRIMARY KEY AUTO_INCREMENT,
    TenSP VARCHAR(100) NOT NULL,
    MoTa TEXT,
    Gia DECIMAL(10,2) NOT NULL CHECK (Gia > 0),
    MaBST INT NOT NULL,
    FOREIGN KEY (MaBST) REFERENCES BoSuuTap(MaBST)
);

CREATE TABLE Size (
    MaSize INT PRIMARY KEY AUTO_INCREMENT,
    SoSize INT NOT NULL
);

CREATE TABLE SanPham_ChiTiet (
    MaSP INT,
    MaSize INT,
    SoLuong INT NOT NULL CHECK (SoLuong >= 0),
    PRIMARY KEY (MaSP, MaSize),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
    FOREIGN KEY (MaSize) REFERENCES Size(MaSize)
);

CREATE TABLE AnhSanPham (
    MaAnh INT PRIMARY KEY AUTO_INCREMENT,
    MaSP INT NOT NULL,
    URL VARCHAR(255) NOT NULL,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE DiaChi (
    MaDC INT PRIMARY KEY AUTO_INCREMENT,
    MaKH INT NOT NULL,
    DiaChiChiTiet VARCHAR(255) NOT NULL,
    GhiChu VARCHAR(100),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE GioHang (
    MaGH INT PRIMARY KEY AUTO_INCREMENT,
    MaKH INT NOT NULL,
    MaSP INT NOT NULL,
    MaSize INT NOT NULL,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaSP, MaSize) REFERENCES SanPham_ChiTiet(MaSP, MaSize)
);

CREATE TABLE Voucher (
    MaVoucher VARCHAR(20) PRIMARY KEY,
    GiamGia DECIMAL(10,2) NOT NULL CHECK (GiamGia >= 0),
    DieuKien DECIMAL(10,2) NOT NULL CHECK (DieuKien >= 0),
    HanSuDung DATE NOT NULL
);

CREATE TABLE HoaDon (
    MaHD INT PRIMARY KEY AUTO_INCREMENT,
    NgayLap DATE NOT NULL,
    TongTien DECIMAL(12,2) NOT NULL CHECK (TongTien >= 0),
    MaKH INT NOT NULL,
    MaNV INT NULL,
    MaDC INT NOT NULL,
    MaVoucher VARCHAR(20),
    TrangThai VARCHAR(50) NOT NULL DEFAULT 'CHO_XU_LY',
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaDC) REFERENCES DiaChi(MaDC)
);

CREATE TABLE ChiTietHoaDon (
    MaHD INT,
    MaSP INT,
    MaSize INT,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    DonGia DECIMAL(10,2) NOT NULL CHECK (DonGia > 0),
    PRIMARY KEY (MaHD, MaSP, MaSize),
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
    FOREIGN KEY (MaSP, MaSize) REFERENCES SanPham_ChiTiet(MaSP, MaSize)
);

CREATE TABLE DanhGia (
    MaKH INT,
    MaSP INT,
    SoSao INT NOT NULL CHECK (SoSao BETWEEN 1 AND 5),
    BinhLuan TEXT,
    NgayDanhGia DATE NOT NULL,
    PRIMARY KEY (MaKH, MaSP),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);
select * from sanpham;


