INSERT INTO `DiaChi` (`MaDC`, `MaKH`, `DiaChiChiTiet`, `GhiChu`) VALUES
(1, 1, 'Trường Yên Ninh Bình', '12h trưa'),
(2, 2, '45 Nguyễn Trãi, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh', 'Văn phòng'),
(3, 3, '77 Lê Lợi, Phường 2, TP. Vũng Tàu, Bà Rịa - Vũng Tàu', 'Giao giờ hành chính'),
(4, 4, '88 Lý Thường Kiệt, Phường 14, Quận Tân Bình, TP. Hồ Chí Minh', NULL),
(5, 5, '212 Trần Phú, Phường 7, Quận 5, TP. Hồ Chí Minh', 'Chung cư Sahom'),
(6, 6, '19B Nguyễn Thị Định, Phường Trung Hoà, Quận Cầu Giấy, Hà Nội', 'Nhà riêng'),
(7, 7, '305 Hùng Vương, Phường 9, Quận 6, TP. Hồ Chí Minh', NULL),
(8, 8, 'Khu 3, Phường Hải Hoà, TP. Móng Cái, Quảng Ninh', 'Gần chợ Móng Cái'),
(9, 9, '50A Bạch Đằng, Phường 2, Quận Tân Bình, TP. Hồ Chí Minh', 'Văn phòng cty'),
(10, 10, '180 Cao Lỗ, Phường 4, Quận 8, TP. Hồ Chí Minh', NULL),
(11, 11, '90 Pasteur, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'Tòa nhà Bitexco'),
(12, 12, '227 Nguyễn Văn Cừ, Phường Hưng Lợi, Quận Ninh Kiều, Cần Thơ', NULL),
(13, 13, '33 Phạm Ngũ Lão, Phường 1, TP. Đà Lạt, Lâm Đồng', 'Khách sạn'),
(14, 14, '101 Tôn Dật Tiên, Phường Tân Phú, Quận 7, TP. Hồ Chí Minh', 'Crescent Mall'),
(15, 15, '56 Hàng Bông, Phường Hàng Bông, Quận Hoàn Kiếm, Hà Nội', NULL),
(16, 16, '235 Khánh Hội, Phường 5, Quận 4, TP. Hồ Chí Minh', 'Nhà riêng'),
(17, 17, '66 Cầu Giấy, Phường Quan Hoa, Quận Cầu Giấy, Hà Nội', 'Văn phòng'),
(18, 18, '120 Nguyễn Du, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh', NULL),
(19, 19, '82 Trần Quang Khải, Phường Tân Định, Quận 1, TP. Hồ Chí Minh', 'Nhà riêng'),
(20, 20, '477 Điện Biên Phủ, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh', 'Pearl Plaza'),
(21, 21, '55 Quang Trung, Phường Hải Châu 1, Quận Hải Châu, Đà Nẵng', NULL),
(22, 22, '15 Hàng Đào, Phường Hàng Đào, Quận Hoàn Kiếm, Hà Nội', 'Cửa hàng'),
(23, 2, '65 Huỳnh Thúc Kháng, Phường Láng Hạ, Quận Đống Đa, Hà Nội', 'Địa chỉ 2'),
(24, 3, '30 Trần Hưng Đạo, Phường 10, Quận 5, TP. Hồ Chí Minh', NULL),
(25, 4, '280 An Dương Vương, Phường 4, Quận 5, TP. Hồ Chí Minh', 'Trường học'),
(26, 5, '11 Sư Vạn Hạnh, Phường 12, Quận 10, TP. Hồ Chí Minh', 'Vạn Hạnh Mall'),
(27, 6, '102 Võ Oanh, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh', 'Nhà riêng'),
(28, 7, '99 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'Văn phòng'),
(29, 8, '44 Tràng Tiền, Phường Tràng Tiền, Quận Hoàn Kiếm, Hà Nội', NULL),
(30, 9, '72 Lê Thánh Tôn, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'Vincom Center'),
(31, 10, '109 Đồng Khởi, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'Opera House'),
(32, 11, '190 Cống Quỳnh, Phường Phạm Ngũ Lão, Quận 1, TP. Hồ Chí Minh', NULL),
(33, 12, '218 Bạch Đằng, Phường 24, Quận Bình Thạnh, TP. Hồ Chí Minh', 'Nhà riêng'),
(34, 13, '52 Nguyễn Chí Thanh, Phường Láng Thượng, Quận Đống Đa, Hà Nội', 'Văn phòng'),
(35, 14, '80 Chùa Láng, Phường Láng Thượng, Quận Đống Đa, Hà Nội', NULL),
(36, 15, '60A Trường Sơn, Phường 2, Quận Tân Bình, TP. Hồ Chí Minh', 'Gần sân bay'),
(37, 16, '37 Tôn Đức Thắng, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'Le Meridien'),
(38, 17, '22 Bà Triệu, Phường Hàng Bài, Quận Hoàn Kiếm, Hà Nội', NULL),
(39, 18, '15A Ngô Văn Sở, Phường 13, Quận 4, TP. Hồ Chí Minh', 'Chung cư'),
(40, 19, '20 Ngô Đức Kế, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'Bitexco'),
(41, 20, '39 Lê Duẩn, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'Diamond Plaza'),
(42, 21, '188 Nguyễn Xí, Phường 26, Quận Bình Thạnh, TP. Hồ Chí Minh', NULL),
(43, 22, '70-72 Lê Thánh Tôn, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'Takashimaya'),
(44, 2, '29 Cát Linh, Phường Cát Linh, Quận Đống Đa, Hà Nội', 'Địa chỉ 3'),
(45, 3, '110 Cầu Giấy, Phường Quan Hoa, Quận Cầu Giấy, Hà Nội', NULL),
(46, 4, '505 Minh Khai, Phường Vĩnh Tuy, Quận Hai Bà Trưng, Hà Nội', 'Times City'),
(47, 5, '10 Trần Nguyên Đán, Phường Định Công, Quận Hoàng Mai, Hà Nội', 'Nhà riêng'),
(48, 6, '88 Láng Hạ, Phường Láng Hạ, Quận Đống Đa, Hà Nội', 'Văn phòng'),
(49, 7, '114 Mai Hắc Đế, Phường Bùi Thị Xuân, Quận Hai Bà Trưng, Hà Nội', NULL),
(50, 8, '24 Hai Bà Trưng, Phường Tràng Tiền, Quận Hoàn Kiếm, Hà Nội', 'Tràng Tiền Plaza'),
(51, 9, '94 Nguyễn Khánh Toàn, Phường Quan Hoa, Quận Cầu Giấy, Hà Nội', 'Địa chỉ 3'),
(52, 1, 'PTIT Hà Nội', 'nhanh nha'),
(53, 1, 'PTIT Hà Nội', '12h trưa'),
(54, 1, 'PTIT Hà Nội', 'nhanh nha'),
(55, 1, 'Trường Yên Ninh Bình', '12h trưa'),
(56, 52, 'Km10, đường Nguyễn Trãi, Quận Hà Đông, Hà Nội.', 'giao nhanh cho tao'),
(57, 1, 'fdsafdsafds', ''),
(58, 1, 'dang', 'dang'),
(59, 1, '1', '1');
